#!/usr/bin/env bash
. "$NIXGG_ROOT/shims/_dispatch.sh"
for a in "$@"; do
  if [[ "$a" == "-c" ]]; then
    exec "$NIXGG_ROOT/compile-driver.sh" cc "$@"
  fi
done
exec "$NIXGG_ROOT/link-driver.sh" cc "$@"
