name: check

on:
  push:
    branches: [master]
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check -L
      - run: bash scripts/verify-override-input.sh
