name: check

on:
  push:
    branches: [master]
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check -L
      - run: nix build .#c .#hello-ccache .#golang .#zig .#rust -L
